#!/bin/bash
TARGET="/home/mediana/$PROJECT_NAME"
REPO="/home/mediana/$PROJECT_NAME.git"
TEMP="/home/mediana/tmp"

GIT_DIR="/home/mediana/$PROJECT_NAME.git"
BRANCH=master
LOGFILE="/home/mediana/$PROJECT_NAME-logs/deploy.log"

print_double() {
    echo -e $1;
    echo -e $1 >> $LOGFILE
}

while read oldrev newrev ref
do
  print_double "Ref $ref received. Deploying ${BRANCH} branch to production..."
  print_double "===== starting deploy $(date) ====="
  print_double "Deploying commit $(git rev-parse --short HEAD) from branch: $BRANCH"

  print_double "Stopping Services"
  sudo systemctl stop daphne celery celerybeat

  # backup database
  # print_double "Backing up database to deploy-$(date).json"
  # cd /home/mediana/$PROJECT_NAME >> $LOGFILE
  # pg_dump -U jaduser -W -w -F c jad > /home/mediana/database-backups/deploy-$(date).zip

  cd /home/mediana/

  # Save untracked files
  cp $TARGET/$PROJECT_NAME/production.py /home/mediana

  # Update files
  print_double "Updating files"
  mkdir -p $TEMP
  git --work-tree=$TEMP --git-dir=$GIT_DIR checkout -f $BRANCH >> $LOGFILE

  rm -rf $TARGET
  mv $TEMP $TARGET
  ##
  
  # Restore untracked files
  mv /home/mediana/production.py $TARGET/$PROJECT_NAME/
 
#    source /home/ubuntu/venv/bin/activate
  cd /home/mediana/$PROJECT_NAME >> $LOGFILE

  print_double "\nrunning npm install"
  npm install
  print_double "\nrunning npm build"
  npm run build
  
  source /home/mediana/venv/bin/activate
  print_double "\nRunning pip install"
  pip install -r requirements.txt >> $LOGFILE
  print_double "\nRunning manage.py migrate"
  env DJANGO_SECRET_KEY=none DJANGO_ALLOWED_HOSTS=127.0.0.1 ./manage.py migrate >> $LOGFILE
  print_double "\nRunning manage.py collectstatic"
  env DJANGO_SECRET_KEY=none DJANGO_ALLOWED_HOSTS=127.0.0.1 ./manage.py collectstatic --noinput >> $LOGFILE

  print_double "\nRestarting services"
  sudo systemctl restart daphne celery celerybeat

  echo "Deployment complete, logs can be found at " $LOGFILE
  print_double "Deployment complete"
done
